check:
	npx @biomejs/biome check --write src

supabase_start:
	npx supabase start

supabase_stop:
	npx supabase stop

studio:
	open http://127.0.0.1:54323

db_dff:
	npx supabase db diff --schema public -f $(FILE)

db_reset:
	npx supabase db reset

db_push:
	npx supabase db push